### PR TITLE
Disable "phpdoc_to_comment" option to avoid false positives with PHPStan @var helpers

### PR DESCRIPTION
**Pull request by alexmanno**

### CODE REVIEW

**Review by Jean85 — APPROVED** [review]
Another possible workaround is https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/5572 by configuring this rule with a list of `ignored_tags` to avoid this. But I fear that the list would be very long, and we would have to keep it updated... So I'm in favor of removing the whole rule.

**Comment by alexmanno** [comment]
@thomasvargiu, could you have some opinion on this?

**Comment by thomasvargiu** [comment]
@alexmanno, @Jean85 I don't consider it a very necessary rule, I agree with this PR.

**Comment by alexmanno** [comment]
@Jean85 please, can you merge and release?

**Comment by Jean85** [comment]
Sure! Can we consider this a patch, since it's removing a rule? I wouldn't count this as a breaking change...

**Comment by alexmanno** [comment]
@Jean85 this change shouldn't be breaking, so imho it can be released as a patch

**Pull request merged**
