### PR TITLE
WIP: Updated rules for v0.4.0

### PR DESCRIPTION
**Pull request by thomasvargiu**
## Default rules
- `visibility_required`
- `heredoc_indentation`
- `heredoc_to_nowdoc`
- `no_null_property_initialization`
- `no_useless_else`
- `no_useless_return`
- `global_namespace_import`
- `constant_case`
## Risky rules
- `fopen_flag_order`
- `fopen_flags`
- `ereg_to_preg`
- `implode_call`
- `no_unset_on_property`

### `visibility_required`

Description of visibility_required rule.
Visibility MUST be declared on all properties and methods; `abstract` and `final` MUST be declared before the visibility; `static` MUST be declared after the visibility.

Fixer is configurable using following option:
* elements (a subset of ['property', 'method', 'const']): the structural elements to fix (PHP >= 7.1 required for `const`); defaults to ['property', 'method']

Fixing examples:
 * Example #1. Fixing with the default configuration.
```diff
--- Original
+++ New
@@ -1,10 +1,10 @@
 <?php
 class Sample
 {
-    var $a;
-    static protected $var_foo2;
+    public $a;
+    protected static $var_foo2;
 
-    function A()
+    public function A()
     {
     }
 }

```

 * Example #2. Fixing with configuration: ['elements' => ['const']].
```diff
--- Original
+++ New
@@ -1,5 +1,5 @@
 <?php
 class Sample
 {
-    const SAMPLE = 1;
+    public const SAMPLE = 1;
 }

```

### `heredoc_indentation`

Description of heredoc_indentation rule.
Heredoc/nowdoc content must be properly indented. Requires PHP >= 7.3.

Fixing examples:
 * Example #1.
```diff
--- Original
+++ New
@@ -1,5 +1,5 @@
 <?php
     $a = <<<EOD
-abc
-    def
-EOD;
+        abc
+            def
+        EOD;

```

 * Example #2.
```diff
--- Original
+++ New
@@ -1,5 +1,5 @@
 <?php
     $a = <<<'EOD'
-abc
-    def
-EOD;
+        abc
+            def
+        EOD;

```

### `heredoc_to_nowdoc`

Description of heredoc_to_nowdoc rule.
Convert `heredoc` to `nowdoc` where possible.

Fixing examples:
 * Example #1.
```diff
--- Original
+++ New
@@ -1,3 +1,3 @@
-<?php $a = <<<"TEST"
+<?php $a = <<<'TEST'
 Foo
 TEST;

```

### `no_null_property_initialization`

Description of no_null_property_initialization rule.
Properties MUST not be explicitly initialized with `null` except when they have a type declaration (PHP 7.4).

Fixing examples:
 * Example #1.
```diff
--- Original
+++ New
@@ -1,4 +1,4 @@
 <?php
 class Foo {
-    public $foo = null;
+    public $foo;
 }

```

### `no_useless_else`

Description of no_useless_else rule.
There should not be useless `else` cases.

Fixing examples:
 * Example #1.
```diff
--- Original
+++ New
@@ -1,6 +1,6 @@
 <?php
 if ($a) {
     return 1;
-} else {
+}  
     return 2;
-}
+

```

### `no_useless_return`

Description of no_useless_return rule.
There should not be an empty `return` statement at the end of a function.

Fixing examples:
 * Example #1.
```diff
--- Original
+++ New
@@ -1,7 +1,7 @@
 <?php
 function example($b) {
     if ($b) {
         return;
     }
-    return;
+    
 }

```

### `global_namespace_import`

Description of global_namespace_import rule.
Imports or fully qualifies global classes/functions/constants.

Fixer is configurable using following options:
* import_constants (false, null, true): whether to import, not import or ignore global constants; defaults to null
* import_functions (false, null, true): whether to import, not import or ignore global functions; defaults to null
* import_classes (false, null, true): whether to import, not import or ignore global classes; defaults to true

Fixing examples:
 * Example #1. Fixing with the default configuration.
```diff
--- Original
+++ New
@@ -1,5 +1,6 @@
 <?php
 
 namespace Foo;
+use DateTimeImmutable;
 
-$d = new \DateTimeImmutable();
+$d = new DateTimeImmutable();

```

 * Example #2. Fixing with configuration: ['import_classes' => true, 'import_constants' => true, 'import_functions' => true].
```diff
--- Original
+++ New
@@ -1,9 +1,12 @@
 <?php
 
 namespace Foo;
+use DateTimeImmutable;
+use function count;
+use const M_PI;
 
-if (\count($x)) {
-    /** @var \DateTimeImmutable $d */
-    $d = new \DateTimeImmutable();
-    $p = \M_PI;
+if (count($x)) {
+    /** @var DateTimeImmutable $d */
+    $d = new DateTimeImmutable();
+    $p = M_PI;
 }

```

 * Example #3. Fixing with configuration: ['import_classes' => false, 'import_constants' => false, 'import_functions' => false].
```diff
--- Original
+++ New
@@ -1,13 +1,13 @@
 <?php
 
 namespace Foo;
 
 use DateTimeImmutable;
 use function count;
 use const M_PI;
 
-if (count($x)) {
-    /** @var DateTimeImmutable $d */
-    $d = new DateTimeImmutable();
-    $p = M_PI;
+if (\count($x)) {
+    /** @var \DateTimeImmutable $d */
+    $d = new \DateTimeImmutable();
+    $p = \M_PI;
 }

```

### `constant_case`

Description of constant_case rule.
The PHP constants `true`, `false`, and `null` MUST be written using the correct casing.

Fixer is configurable using following option:
* case ('lower', 'upper'): whether to use the `upper` or `lower` case syntax; defaults to 'lower'

Fixing examples:
 * Example #1. Fixing with the default configuration.
```diff
--- Original
+++ New
@@ -1,4 +1,4 @@
 <?php
-$a = FALSE;
-$b = True;
-$c = nuLL;
+$a = false;
+$b = true;
+$c = null;

```

### `fopen_flag_order`

Description of fopen_flag_order rule.
Order the flags in `fopen` calls, `b` and `t` must be last.

Fixer applying this rule is risky.
Risky when the function `fopen` is overridden.

Fixing examples:
 * Example #1.
```diff
--- Original
+++ New
@@ -1,2 +1,2 @@
 <?php
-$a = fopen($foo, 'br+');
+$a = fopen($foo, 'r+b');

```

### `fopen_flags`

Description of fopen_flags rule.
The flags in `fopen` calls must omit `t`, and `b` must be omitted or included consistently.

Fixer applying this rule is risky.
Risky when the function `fopen` is overridden.

Fixer is configurable using following option:
* b_mode (bool): the `b` flag must be used (`true`) or omitted (`false`); defaults to true

Fixing examples:
 * Example #1. Fixing with the default configuration.
```diff
--- Original
+++ New
@@ -1,2 +1,2 @@
 <?php
-$a = fopen($foo, 'rwt');
+$a = fopen($foo, 'rwb');

```

 * Example #2. Fixing with configuration: ['b_mode' => false].
```diff
--- Original
+++ New
@@ -1,2 +1,2 @@
 <?php
-$a = fopen($foo, 'rwt');
+$a = fopen($foo, 'rw');

```

### `ereg_to_preg`

Description of ereg_to_preg rule.
Replace deprecated `ereg` regular expression functions with `preg`.

Fixer applying this rule is risky.
Risky if the `ereg` function is overridden.

Fixing examples:
 * Example #1.
```diff
--- Original
+++ New
@@ -1,1 +1,1 @@
-<?php $x = ereg('[A-Z]');
+<?php $x = preg_match('/[A-Z]/D');

```

### `implode_call`

Description of implode_call rule.
Function `implode` must be called with 2 arguments in the documented order.

Fixer applying this rule is risky.
Risky when the function `implode` is overridden.

Fixing examples:
 * Example #1.
```diff
--- Original
+++ New
@@ -1,2 +1,2 @@
 <?php
-implode($pieces, '');
+implode('', $pieces);

```

 * Example #2.
```diff
--- Original
+++ New
@@ -1,2 +1,2 @@
 <?php
-implode($pieces);
+implode('', $pieces);

```

### `no_unset_on_property`

Description of no_unset_on_property rule.
Properties should be set to `null` instead of using `unset`.

Fixer applying this rule is risky.
Changing variables to `null` instead of unsetting them will mean they still show up when looping over class variables. With PHP 7.4, this rule might introduce `null` assignments to property whose type declaration does not allow it.

Fixing examples:
 * Example #1.
```diff
--- Original
+++ New
@@ -1,2 +1,2 @@
 <?php
-unset($this->a);
+$this->a = null;

```

### CODE REVIEW

**Comment by thomasvargiu** [comment]
Script to create description:

```php
<?php

$rules = [
    'visibility_required' => ['property', 'method', 'const'],
    'heredoc_indentation' => true,
    'heredoc_to_nowdoc' => true,
    'no_null_property_initialization' => true,
    'no_useless_else' => true,
    'no_useless_return' => true,
    'global_namespace_import' => [
        'import_classes' => true,
        'import_constants' => true,
        'import_functions' => true,
    ],
    'constant_case' => true,
];

$riskyRules = [
    'fopen_flag_order' => true,
    'fopen_flags' => true,
    'ereg_to_preg' => true,
    'implode_call' => true,
    'no_unset_on_property' => true,
];

function printRules(array $rules): string
{
    $replaceDiff = static function (string $text): string {
        $exploded = explode("\n", $text);
        $inside = false;
        $trim = 0;
        $lines = [];
        foreach ($exploded as $line) {
            if (false !== ($pos = strpos($line, '---------- begin diff ----------'))) {
                $inside = true;
                $lines[] = '```diff';
                $trim = $pos;
            } elseif (strpos($line, '----------- end diff -----------')) {
                $inside = false;
                $lines[] = '```';
                $trim = 0;
            } elseif ($inside) {
                $lines[] = substr($line, $trim);
            } else {
                $lines[] = $line;
            }
        }

        return implode("\n", $lines);
    };

    return implode("\n", array_map(static function (string $name) use ($replaceDiff): string {
        return sprintf("### `%s`\n\n%s\n", $name, $replaceDiff(shell_exec('./vendor/bin/php-cs-fixer describe ' . $name)));
    }, array_keys($rules)));
}

function printMenu(array $rules, array $riskyRules)
{
    $printMenu = static function (string $name, array $rules) {
        echo '## ' . $name . PHP_EOL;
        array_map(static function (string $name) {
            echo sprintf('- `%s`', $name) . PHP_EOL;
        }, $rules);
    };
    $printMenu('Default rules', array_keys($rules));
    $printMenu('Risky rules', array_keys($riskyRules));
}

printMenu($rules, $riskyRules);
echo PHP_EOL;
echo "## Default Rules" . PHP_EOL;
echo printRules($rules);

echo "## Risky Rules" . PHP_EOL;
echo printRules($riskyRules);
```

**Comment by thomasvargiu** [comment]
Test slack comment

**Comment by Jean85** [comment]
We should bump all of this to 0.5.
Also, CS Fixer 2.18 has PSR-12 support, we should use it.

**Comment by Jean85** [comment]
This PR should be completely revisited due to #32.

**Comment by thomasvargiu** [comment]
Consider to add:
```
'comment_to_phpdoc' => true,
'phpdoc_to_comment' => false,
```

Disabling `phpdoc_to_comment` because does not work well when we need to override var types.

**Comment by Jean85** [comment]
> This PR should be completely revisited due to https://github.com/facile-it/facile-coding-standard/pull/32.

Also due to #42, and too many code conflicts. Closing, will reopen new, multiple ones.

**Pull request closed without merging**
