### PR TITLE
Add supporto to Symfony 6.0

### PR DESCRIPTION
**Pull request by dzanfardino**

### CODE REVIEW

**Review by Jean85 — APPROVED** [review]
Change is fine, and the CI is running with `symfony/console` 6, so we've tested it: https://github.com/facile-it/facile-coding-standard/runs/4506406904?check_suite_focus=true#step:4:111

But, in reality, `composer/composer` 2.1.14 is not compatible with it, so we're getting a downgrade to .13 to be able to install Symfony 6.

On one hand, we're fine and we're provably compatible with Symfony 6; OTOH, we have a possible fragile CI...

**Comment by Jean85** [comment]
IMHO there's no compat issue on our side, but maybe we should add a dedicated CI job that forces the requirement on Symfony 6, so we can be sure that our CI runs that too. Otherwise, we could find ourselves blind once Composer 2.2 is out, since it has not Symfony 6 compat and the Composer SAT resolver could choose to install that and Symfony 5 instead. In that way, either the CI does the downgrade and tests it anyway, or it fails (and we will fix it somehow).

**Comment by dzanfardino** [comment]
@Jean85 can this be merged ?

**Comment by Jean85** [comment]
Not without testing against that explicitly. We would need another CI job that, leveraging Symfony Flex, forces Symfony 6 and tests it.

You can look at how to do it here: https://github.com/getsentry/sentry-symfony/blob/c3f2c687b45e3e42573372ac75e643c9e4f3f896/.github/workflows/tests.yaml#L16

**Pull request merged**
